// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function FetchModels(arg1, arg2) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2);
}

export function LoadLocalization(arg1) {
  return window['go']['main']['App']['LoadLocalization'](arg1);
}

export function SaveRow(arg1, arg2) {
  return window['go']['main']['App']['SaveRow'](arg1, arg2);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function StartTranslation(arg1) {
  return window['go']['main']['App']['StartTranslation'](arg1);
}

export function StopTranslation() {
  return window['go']['main']['App']['StopTranslation']();
}

export function TranslateRow(arg1, arg2) {
  return window['go']['main']['App']['TranslateRow'](arg1, arg2);
}
