// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseFolder():Promise<string>;

export function FetchModels(arg1:string,arg2:string):Promise<Array<main.ModelInfo>>;

export function LoadLocalization(arg1:string):Promise<main.LocalizationDocument>;

export function SaveRow(arg1:number,arg2:string):Promise<main.LocalizationRow>;

export function SetPaused(arg1:boolean):Promise<void>;

export function StartTranslation(arg1:main.TranslateOptions):Promise<main.TranslationSummary>;

export function StopTranslation():Promise<void>;

export function TranslateRow(arg1:number,arg2:main.TranslateOptions):Promise<string>;
